// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("dragging", ["mouseCapture"]).factory("dragging", function($rootScope, mouseCapture) {
    var threshold;
    threshold = 1;
    return {
      startDrag: function(evt, config) {
        var dragging, mouseMove, mouseUp, released, x, y;
        dragging = false;
        x = evt.pageX;
        y = evt.pageY;
        mouseMove = function(evt) {
          if (!dragging) {
            if (Math.abs(evt.pageX - x) > threshold || Math.abs(evt.pageY - y) > threshold) {
              dragging = true;
              if (config.dragStarted) {
                config.dragStarted(x, y, evt);
              }
              if (config.dragging) {
                config.dragging(evt.pageX, evt.pageY, evt);
              }
            }
          } else {
            if (config.dragging) {
              config.dragging(evt.pageX, evt.pageY, evt);
            }
            x = evt.pageX;
            y = evt.pageY;
          }
        };
        released = function() {
          if (dragging) {
            if (config.dragEnded) {
              config.dragEnded();
            }
          } else {
            if (config.clicked) {
              config.clicked();
            }
          }
        };
        mouseUp = function(evt) {
          mouseCapture.release();
          evt.stopPropagation();
          evt.preventDefault();
        };
        mouseCapture.acquire(evt, {
          mouseMove: mouseMove,
          mouseUp: mouseUp,
          released: released
        });
        evt.stopPropagation();
        evt.preventDefault();
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=drag_service.map
*/
