// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("mouseCapture", []).factory("mouseCapture", function($rootScope) {
    var mouseCaptureConfig, mouseMove, mouseUp, target;
    target = document;
    mouseCaptureConfig = null;
    mouseMove = function(evt) {
      if (mouseCaptureConfig && mouseCaptureConfig.mouseMove) {
        mouseCaptureConfig.mouseMove(evt);
        $rootScope.$digest();
      }
    };
    mouseUp = function(evt) {
      if (mouseCaptureConfig && mouseCaptureConfig.mouseUp) {
        mouseCaptureConfig.mouseUp(evt);
        $rootScope.$digest();
      }
    };
    return {
      registerElement: function(element) {
        target = element;
      },
      acquire: function(evt, config) {
        this.release();
        mouseCaptureConfig = config;
        target.mousemove(mouseMove);
        target.mouseup(mouseUp);
      },
      release: function() {
        if (mouseCaptureConfig) {
          if (mouseCaptureConfig.released) {
            mouseCaptureConfig.released();
          }
          mouseCaptureConfig = null;
        }
        target.unbind("mousemove", mouseMove);
        target.unbind("mouseup", mouseUp);
      }
    };
  }).directive("mouseCapture", function() {
    return {
      restrict: "A",
      controller: function($scope, $element, $attrs, mouseCapture) {
        return mouseCapture.registerElement($element);
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=mouse_capture_service.map
*/
