// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("syslog", []).service("syslogService", function() {
    var syslog, syslogService;
    // syslog = require('./node_modules/insta-syslog/syslog');
    syslog = {}
    syslogService = syslog;
    console.log('[Info] This is syslog service.');
    return syslogService;
  });

}).call(this);

//# sourceMappingURL=syslogservice.map
